---
galaxy_info:
  author: shantanu jain
  description: installion of iptables
  license: Nexus

  min_ansible_version: 2.2

  platforms:
  - name: EL
    versions: 7

  galaxy_tags:
  - iptables 

dependencies: []
